name: "Lint & Test"
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build golangci-lint from source
        run: |
          git clone https://github.com/golangci/golangci-lint.git /tmp/golangci-lint
          cd /tmp/golangci-lint
          # Use the Go 1.23 toolchain that was set up by actions/setup-go
          export GOROOT=$(go env GOROOT)
          export PATH=$(go env GOROOT)/bin:$PATH
          go build -o golangci-lint ./cmd/golangci-lint
          sudo mv golangci-lint /usr/local/bin/
      - name: Run golangci-lint
        run: golangci-lint run
  golangci-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: golangci-test
        run: go test ./... -coverprofile=profile.cov -cover
      - name: send coverage data
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
