name: "Lint & Test"
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
  golangci-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: golangci-test
        run: go test ./... -v -coverprofile=profile.cov -cover
      - name: send coverage data
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
